lang: EN
counry: US

redis:
  host: localhost
  port: 6379

articles:
  path: data/articles

collections:
  globalvoices: 
    path: data/globalvoices
    filename: globalvoicesonline.wordpress.2011-jan-feb.xml

