lang: EN
counry: US

redis:
  host: localhost
  port: 6379

articles:
  path: data/articles

collections:
  globalvoices: 
    path: data/globalvoices
    output: data/globalvoices/articles
    filename: globalvoicesonline.wordpress.2011-jan-feb.xml
  globalvoices7: 
    path: data/globalvoices7
    output: data/globalvoices7/articles

